name: wi_vi_app
description: "Wi-Vi App for WiFi monitoring and security."
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2 
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  provider: ^6.1.0
  glassmorphism: ^3.0.0
  http: ^1.2.0
  # Firebase Dependencies (Keep for Android & iOS)
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  firebase_auth: ^5.5.1
  shared_preferences: ^2.5.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/wivi_logo.png
    - assets/google.png
    - assets/facebook.png
    - assets/github.png


